name: xp-app-build
description: This is an action to automate Enonic XP applications build
author: Enonic AS (https://enonic.com)
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11

    - uses: gradle/actions/setup-gradle@v4

    - run: ./gradlew build -Pcom.enonic.xp.app.production=true
      shell: bash
